### ISSUE TITLE
Overview Tab

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#100]
There is plenty of unused space at the bottom, so it might as well be used for one or even two new tabs.

Suggestion for a new tab: 

**SNAPSHOT**

01. No. of apps in Active Profile: Z (x/y)
02. No. of apps in Managed User Profile(s), excluding Clones: x
03. No. of apps sideloaded from external sources: x
04. No. of apps with 'Install from Unknown Sources' enabled*: Z (x/y)
05. No. of apps with 'Accessibility' permissions*: Z (x/y)
06. No. of apps that can 'Appear on Top'*: Z (x/y)
07. No. of apps with 'Device Admin' permissions*: Z (x/y)
08. No. of apps that have 'No Internet' permissions**: Z (x/y)
09. No. of apps with clones in other profiles: Z (x/y)
10. No. of apps with SharedUserID: Z (x/y)

Bootloader: Locked (in green)/ Unlocked (in red)
Root: Available (in red)/ Unavailable (in green)
USB Debugging: Enabled (in red)/ Disabled (in green)

Last updated:

Refresh button (app should refresh automatically on every launch, as well as when refresh button is pressed in any of the tabs).

The 'Z (x/y)' format is Total (user apps/ system apps).

_*the total here will only count apps in the active profile. Also, each of these will be a shortcut to the respective permissions within the app._

_** the number here is the total of apps that have no internet permissions AND that do not share their ID with other app(s) that have internet permissions. Apps like the one mentioned in #99 should also be excluded, if you find a way to filter such apps._

**Comment by d4rken** [comment]
> There is plenty of unused space at the bottom,

Do you men adding a 3rd page + icon on the bottom tab bar?

**Comment by TheMysticS** [comment]
> > There is plenty of unused space at the bottom,
> 
> Do you men adding a 3rd page + icon on the bottom tab bar?

That's correct. And preferably as the 1st Tab (i.e. to the left of Apps Tab).

By default, Permission Pilot must open with the Apps Tab on launch, although you can let the user customize this behaviour.

**Comment by d4rken** [comment]
These infos can't really be retrieved:

> Bootloader: Locked (in green)/ Unlocked (in red)
> Root: Available (in red)/ Unavailable (in green)
> USB Debugging: Enabled (in red)/ Disabled (in green)

**Comment by d4rken** [comment]
> No. of apps with 'Install from Unknown Sources' enabled*: Z (x/y)
No. of apps with 'Accessibility' permissions*: Z (x/y)
No. of apps that can 'Appear on Top'*: Z (x/y)
No. of apps with 'Device Admin' permissions*: Z (x/y)
No. of apps that have 'No Internet' permissions**: Z (x/y)
No. of apps with clones in other profiles: Z (x/y)
No. of apps with SharedUserID: Z (x/y)

Not sure how useful these will be, feels bloaty, adding them as test though.
