### ISSUE TITLE
Count of apps in each permission category

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#101]
![iMarkup_20220727_105119](https://user-images.githubusercontent.com/54448474/181167663-124ccf40-b760-431a-b819-38c9e9bbdf44.png)

Can you add the information above in each permission category?

Total should be in bold font.

**Comment by TheMysticS** [comment]
How about this:

User Apps: Granted to 4 out of 10 apps (40%).
System Apps: Granted to 8 out of 25 apps (32%).
Total: Granted to 12 out of 35 apps (34.29%).

**Comment by TheMysticS** [comment]
I hope these numbers do NOT include apps installed in Managed User Profiles.

Assuming they aren't included in the calculations, and since those apps show up in the Permissions screen, can you add one more line beneath the calculations:

**Due to Android restrictions, status of permissions granted to apps installed in other user profiles cannot be determined. As such, those apps have been excluded from the computations above.**

**Comment by TheMysticS** [comment]
>
Due to Android restrictions, status of permissions granted to apps installed in other user profiles cannot be determined. As such, those apps have been excluded from the computations above.
>
If the above is too long, then something like this would be fine too:

User Apps*: Granted to 4 out of 10 apps (40%).
System Apps*: Granted to 8 out of 25 apps (32%).
Total*: Granted to 12 out of 35 apps (34.29%).

_*apps installed in other user profiles are not part of this computation due to Android restrictions._

**Comment by TheMysticS** [comment]
> **Due to Android restrictions, status of permissions granted to apps installed in other user profiles cannot be determined. As such, those apps have been excluded from the computations above.**
>

If the above is too long, then something like this would be fine too:

User Apps*: Granted to 4 out of 10 apps (40%).
System Apps*: Granted to 8 out of 25 apps (32%).
Total*: Granted to 12 out of 35 apps (34.29%).

_*apps installed in other user profiles are not part of this computation due to Android restrictions._

**Comment by d4rken** [comment]
I think apps in other profiles are included at the moment.

Not a fan of all the extra texts and explanations, showing these numbers is "eye candy", having to add disclaimers to every info makes the UI cluttered and difficult to understand.
Theoretically the disclaimer only needs to be shown if there even is another profile, now we need 2x the texts?

mhhhhh I'll revisit this

**Comment by TheMysticS** [comment]
Information presented must be accurate, and there should be full disclosure of limitations, wherever necessary.

If you can hide that info where managed user profiles do not exist, that would be wonderful. I'm not sure how much work that would entail.

AFAIK, this is only the 2nd instance where such a disclosure has been suggested. I have kept it short so that it conveys the message without taking too much space.

If required, we can reword the text in the other place too and make it short as before.

**Comment by d4rken** [comment]
> AFAIK, this is only the 2nd instance where such a disclosure has been suggested. I have kept it short so that it conveys the message without taking too much space.

True, it was hyperbole, sorry.

I've adjusted calculations and it should no longer include packages from other profiles.
If there was a difference, i.e. filtered != unfiltered, then the disclaimer is displayed.

Text is super long, I've adjusted it a bit, but you can send a PR to edit it further after the next build.

**Comment by d4rken** [comment]
I've removed the total amount of apps display, this seem not useful to the user.

**Comment by TheMysticS** [comment]
That one additional like would be good to have though, even if not too important.
