### ISSUE TITLE
Sideloaded Apps Filter

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#110]
Apps whose install source is not identifiable are being included with Sideloaded Apps.

I think if an app has been Sideloaded, PP can definitely identify the source. So please exclude apps which have install source as 'Information Not Available' from this filter.

In this context, I hope PP can identify apps Sideloaded via ADB. Such apps must be included with Sideloaded Apps filter.

**Comment by TheMysticS** [comment]
Based on what you said here:

https://github.com/d4rken-org/permission-pilot/issues/111#issuecomment-1198183404

Is it a safer to leave this filter as it is at the moment?

**Comment by d4rken** [comment]
I think the current `sideloaded = !isSystemApp && installer == null` is a good compromise, it's useful and not really wrong either.

**Comment by TheMysticS** [comment]
So can we close this ticket? Or would you like to take a look at it later?
