### ISSUE TITLE
Apps without internet access

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#112]
Apps without internet access, but sharing ID with other app(s) which are installed AND having internet access: are these excluded from this filter?

Does PP perform this check?

**Comment by TheMysticS** [comment]
An app (X) that doesn't have internet permissions of its own, but still consumes data using SharedUserID feature of another app (Y): to which app does the system attribute this data consumption to? X or Y?

**Comment by d4rken** [comment]
Code for determining the `InternetAccess`:
https://github.com/d4rken-org/permission-pilot/blob/db08332d722460058a12bd9678c8732a32300fd0/app/src/main/java/eu/darken/myperm/apps/core/container/PrimaryProfilePkg.kt#L65-L72

Filter code:
https://github.com/d4rken-org/permission-pilot/blob/db08332d722460058a12bd9678c8732a32300fd0/app/src/main/java/eu/darken/myperm/apps/ui/list/AppsFilterOptions.kt#L58-L65

So the filter will show apps with indirect internet access, but they will be marked with a different icon.

> An app (X) that doesn't have internet permissions of its own, but still consumes data using SharedUserID feature of another app (Y): to which app does the system attribute this data consumption to? X or Y?

Y
The system doesn't know what the purpose of the data is that is send from X to Y.

**Comment by TheMysticS** [comment]
>
> 
> So the filter will show apps with indirect internet access, but they will be marked with a different icon.
> 
So PP does check for both direct and indirect internet access, and this filter will only show apps that have no internet access either directly or indirectly?

> >
> Y
> The system doesn't know what the purpose of the data is that is send from X to Y.
>
Okay. Thanks for clarifying.
