### ISSUE TITLE
Сrash after clicking on any app in the list

### ISSUE THREAD

**Issue by tommynok** [d4rken-org/permission-pilot#116]
OS MM
Permission Pilot v0.5.7

[logs-2022-07-29-02-12-45.zip](https://github.com/d4rken-org/permission-pilot/files/9214806/logs-2022-07-29-02-12-45.zip)
[eu.darken.myperm_logfile_1659049364259.log.zip](https://github.com/d4rken-org/permission-pilot/files/9214807/eu.darken.myperm_logfile_1659049364259.log.zip)

**Comment by d4rken** [comment]
Duplicate of #113
