### ISSUE TITLE
Reorder a Filter in Apps Tab

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#120]
Can you move the 'Apps without internet access' filter to the 6th place, i.e. between Sideloaded Apps and Shared User ID?

This will keep related filters together.

**Comment by d4rken** [comment]
Sure, or if you want to do it yourself:

https://github.com/d4rken-org/permission-pilot/blob/b5569fb9d9236267d884c9e8bdb44a91199c70db/app/src/main/java/eu/darken/myperm/apps/ui/list/AppsFilterOptions.kt
