### ISSUE TITLE
Restructure permission filters

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/permission-pilot#127]
The `Core` filter might not be too useful. I'm thinking

* Core: Every permission that is officially available to Android DEVs: https://developer.android.com/reference/android/Manifest.permission
* System apps: All permissions defined by system apps
* User apps: All permissions defined by user apps

And then 3 filter that define the "type":
* Runtime permission: User gets popup
* Special access: User has to go to some system screen
* Granted by default: Apps just get these under thread of Google Play sanctions

That should cover the most common scenarios? The user can still search everything too.

The groups that we have give the user a less cluttered view, so they dont have to view 600 permissions if they are looking for something related to connectivity, they can just open that group. Maybe group is the wrong word. Maybe we name it category?
They don't have many duplicates either, I think currently it's only the `BLUETOOTH_SCAN` permission that is both "connectivity" and "location".

_Originally posted by @d4rken in https://github.com/d4rken-org/permission-pilot/issues/124#issuecomment-1200266673_

**Comment by TheMysticS** [comment]
Correct terminology would be as follows:

**Group is a subset of Category.**

Example:

Category could be Privacy.

One Group under this category would be set of permissions requesting access to sensors.

Another group under this category would be set of permissions requesting access to call logs, sms, etc.
