### ISSUE TITLE
Permission icon is a direct link to corresponding System Settings

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#128]
Just as with Apps Tab, please make the group icons on the Permissions Tab act as direct link to the corresponding System Settings page, which would either be under **Permissions Manager** or under **Special Access**, or others as applicable.

Clicking anywhere else will have the current behaviour or expansion/ collapse.

**Comment by d4rken** [comment]
Underlying issue is the same as #119 
No official way to do these, only ROM specific ways (if even possible on all ROMs).

**Comment by TheMysticS** [comment]
For now, you can consider limiting these to just the standard options that are available in all (or most) ROMs. I think the Permission Manager and Special Access entries are common to all (or most) ROMs.

[Permission Controller](https://user-images.githubusercontent.com/54448474/182084999-e4888240-d392-4a2a-8be1-7174444fa3b6.jpg)

[Special Access](https://user-images.githubusercontent.com/54448474/182085030-30099dc3-16d1-4bad-923a-9c8c6f46bf5d.jpg)

**Comment by TheMysticS** [comment]
In v0.7.0, which combination of filters will allow the user to see just the permissions covered under the above two?

**Comment by d4rken** [comment]
> I think the Permission Manager and Special Access entries are common to all (or most) ROMs.

LIkely exists on most ROMs, but there is no official API to open these. The permission manager has no intents that I could find, and the "Special Access" page does not have an intent for the top level page, just direct intents for ~65% of the permissions.

> In v0.7.0, which combination of filters will allow the user to see just the permissions covered under the above two?

AOSP + declared by system + not granted automatically

[Screenshot from 2022-08-01 10-17-11](https://user-images.githubusercontent.com/1439229/182104827-6bf9c04a-bef7-465b-a189-fa67b696e5f6.png)

**Comment by TheMysticS** [comment]
> LIkely exists on most ROMs, but there is no official API to open these. The permission manager has no intents that I could find, and the "Special Access" page does not have an intent for the top level page, just direct intents for ~65% of the permissions.
> 
I'm referring to opening the direct intents only, wherever available for those covered by the above two.

I'll prepare a PR soon, and I'll also list the intents to make it easy for you.


> AOSP + declared by system + not granted automatically
> 
> [Screenshot from 2022-08-01 10-17-11](https://user-images.githubusercontent.com/1439229/182104827-6bf9c04a-bef7-465b-a189-fa67b696e5f6.png)
>
I think there are some additional (and may be missing) permissions showing up. I'll go through in detail and get back.

**Comment by d4rken** [comment]
Please make a new ticket for it. #128 is not about which permissions are there or not there...
