### ISSUE TITLE
Keep Camera and Microphone separate

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#131]
On pretty much all the ROMs, Camera and Microphone are separate entries, and Body Sensors are a group of its own.

You have clubbed them all under Sensors.

PP too must stick with the same classification as presented in ROMs.

**Comment by d4rken** [comment]
Not a fan of this. It would be two groups with just a single permission in it, huge waste of space.
I would consider adding something like a "recording" group that contains both camera and microphone.

> PP too must stick with the same classification as presented in ROMs.

I disagree, the system spreads permissions over multiple menus and multiple screens, this can be done better.
e.g.  the system "Permissions manager" keeps SMS and "Instant messages" separate is, but merges different file permissions :shrug:

**Comment by TheMysticS** [comment]
> Not a fan of this. It would be two groups with just a single permission in it, huge waste of space. I would consider adding something like a "recording" group that contains both camera and microphone.
> 
The suggestion above is to show the permissions just as user would find under system settings in most ROMs.

> I disagree, the system spreads permissions over multiple menus and multiple screens, this can be done better. e.g. the system "Permissions manager" keeps SMS and "Instant messages" separate is, but merges different file permissions 🤷
>
This falls under reorganization of Permissions. Might as well consider new categories like Privacy, Security and others?
