### ISSUE TITLE
Open App button

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#135]
![iMarkup_20220802_193814](https://user-images.githubusercontent.com/54448474/182397094-38656fb4-55d1-4d07-a017-a176520f30a3.png)

Instead of rectangular box, you may consider implementing an elliptical box, preferably with background colour extracted from the primary colour of the app icon. 🙂

**Comment by d4rken** [comment]
Extracting primary colors would be too much work for me, (someone else can work on that if they want?).
Adding a more visible open text button could go into v1 still.

**Comment by TheMysticS** [comment]
> Extracting primary colors would be too much work for me, (someone else can work on that if they want?). Adding a more visible open text button could go into v1 still.

Then leave the beautification part out for now. A simple button would do just fine.
