### ISSUE TITLE
Special Usage filter

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#139]
Can you add the following permissions too to this filter:

1. WiFi Control (CHANGE_WIFI_STATE)

2. DND Permission (ACCESS_NOTIFICATION_POLICY)

3. Ignore Battery Optimization (REQUEST_IGNORE_BATTERY_OPTIMIZATIONS)

4. Device Admin Apps

5. Picture-in-Picture (if possible)

6. VR Helper Services

Also, rename the filter to Special Access (to stick with Google's terminology)

**Comment by d4rken** [comment]
I also added Picture-in-Picture as we some support for it already.
For the others more core work is necessary.
