### ISSUE TITLE
Where you downloaded the apps from

### ISSUE THREAD

**Issue by Wjxfi** [d4rken-org/permission-pilot#157]
more

sai
total commander
lucky patcher
appgallery
unpacking applications:
apk
apkm
apks
xapk
sapk (alpha backup)

**Comment by d4rken** [comment]
Downloading apks is out of scope.
Smarter logic to open app stores, like #158 is more within scope.

**Comment by d4rken** [comment]
I'm not sure what you mean, please elaborate.

If the installing app sets the information (which is optional on some Android version), then PP should display the sources already.

For app stores we have icons:
https://github.com/d4rken-org/permission-pilot/blob/441ad924f368999712d2f0791abffa8c26374147/app/src/main/java/eu/darken/myperm/apps/core/known/AKnownPkg.kt#L38-L40
