### ISSUE TITLE
Google Play Release

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/permission-pilot#16]
Do we? Do I? want this?

- [x] Graphic Assets
- [x] Screenshots
- [x] Description texts (could use the ones provided by @IzzySoft)
- [x] Can we automate releases via fastlane

**Comment by dragonGod97677** [comment]
I agree on description and automate release

**Comment by IzzySoft** [comment]
I'd strongly suggest including at least some screenshots with your Fastlane structure. People are much more like taking a closer look if they have some visual impression. Should you use Fastlane binaries to automate playstore release, the very same screenshots would be deployed there as well (including icon and featureGraphic, if you included them). So "one ring to rule them all" :wink:

**Comment by d4rken** [comment]
Of course, 2 screenshots are mandatory for gplay anyways :wink:. 

My fastlane skills are a bit rusty, ideally I would like to have this all very automated, more automated than my other apps, seeing as this a fresh project where things can go a bit wrong at the start :grin: 

Does fastlane support bundle signing + upload? :thinking: 
Last time I set fastlane app, we could all still use APKs :smiling_face_with_tear:

**Comment by IzzySoft** [comment]
I've no idea about details on what the fastlane binaries can achieve, sorry – I work with the structures/metadata only. As bundles are now rather mandatory at Play (and devs have to hand over their private parts… ahem, signing keys – and thus should better use [diffoscope](https://diffoscope.org/)¹ on the resulting APKs to make sure nothing was added), I'd expect it to support them, though.

> My fastlane skills are a bit rusty

If you let me know and can cross-check once the structures are up, just send me a ping then. I'll have to do that anyway to tell my updater what to pick and how to handle it.

----

¹ <sub>F-Droid uses diffoscope for reproducible builds</sub>

**Comment by d4rken** [comment]
> As bundles are now rather mandatory at Play (and devs have to hand over their private parts… ahem, signing keys – and thus should better use [diffoscope](https://diffoscope.org/)¹ on the resulting APKs to make sure nothing was added), I'd expect it to support them, though.

Yeah huge dislike from my end too. Actually rushed out a (yet to be released) alpha pre-deadline to still get grandfathered into the APK only option...

> If you let me know and can cross-check once the structures are up, just send me a ping then. I'll have to do that anyway to tell my updater what to pick and how to handle it.

Will do :heart:

**Comment by IzzySoft** [comment]
Hehe… heard of several devs applying for the "grandfathering option". A pity such a thing is necessary.

Looking forward to your ping then!

**Comment by dragonGod97677** [comment]
Ill provide screenshots when the permissions tab is sorted out.

**Comment by IzzySoft** [comment]
Just let me know when they are there in Fastlane so I can tell my updater ow to handle them. Thanks!

**Comment by dragonGod97677** [comment]
> @dragonGod97677 what do you think about the current permissions tab?

It's perfectly fine, I'll create a issue ticket when theres need a adjustment or something

**Comment by d4rken** [comment]
@dragonGod97677 v0.9.0 currently building, I think we can take a few screenshots for Google Play now, what do you think?

**Comment by dragonGod97677** [comment]
> @dragonGod97677 v0.9.0 currently building, I think we can take a few screenshots for Google Play now, what do you think?

Sure, you can put some, here's the screenshots
[Permission Pilot Screenshots.zip](https://github.com/d4rken-org/permission-pilot/files/9400462/Permission.Pilot.Screenshots.zip)

**Comment by dragonGod97677** [comment]
[Permission Pilot Screenshots.zip](https://github.com/d4rken-org/permission-pilot/files/9400899/Permission.Pilot.Screenshots.zip)
Here's the screenshots, I've done some oopies so.... i have to re-zip it and reupload it

**Comment by d4rken** [comment]
@IzzySoft https://github.com/d4rken-org/permission-pilot/tree/main/fastlane/metadata/android/en-US/images does that work for you?

**Comment by IzzySoft** [comment]
@d4rken thanks, but the structure needs a little adjustment. Can you create a `phoneScreenshots` directory inside `images/` and move the screenshots there (leaving icon & featureGraphic where they are)?

**Comment by d4rken** [comment]
Like this? https://github.com/d4rken-org/permission-pilot/commit/8a2d406faec085285585ad856e232479cf03f601

**Comment by IzzySoft** [comment]
Perfect, yes! I've already placed them here manually so you don't need to wait for the release to have them showing up – they will with the next sync today at around 6 pm UTC. Thanks a lot!

**Comment by IzzySoft** [comment]
PS: as for https://github.com/d4rken-org/permission-pilot/tree/main/fastlane/metadata/android/en-US/changelogs – file names there should be `<versionCode>.txt` so they show up for the matching release :wink:

**Comment by d4rken** [comment]
> PS: as for https://github.com/d4rken-org/permission-pilot/tree/main/fastlane/metadata/android/en-US/changelogs – file names there should be `<versionCode>.txt` so they show up for the matching release wink If you let me know once those are there, I can enable them as well.

A default shows up by `default` for all other releases :wink: 
I won't be creating manual release notes for for most Google Play release.
Trying to keep overhead for updating the app low.
Have not found a good way to automate this.

**Comment by IzzySoft** [comment]
OK, no prob – was just mentioning it as the corresponding directory was there. If you usually put a summary like on [v0.9.0-RC0](https://github.com/d4rken-org/permission-pilot/releases/tag/v0.9.0-RC0) I could instead add a changelog link to the app listing in general, so users can follow that. Just if you want, no pressure.

**Comment by d4rken** [comment]
> If you usually put a summary like on [v0.9.0-RC0](https://github.com/d4rken-org/permission-pilot/releases/tag/v0.9.0-RC0) I could instead add a changelog link to the app listing in general, so users can follow that. Just if you want, no pressure.

The changelogs on Github are generated, v0.9.0 looks nice because i did some features via PRs (required for the generation) instead of direct pushes to `main`.

I have not found a nice way to generate changelogs based on both PRs and commits.

If the app becomes more popular I will be a bit more tidy and do more things via PRs so changelogs should be nicer :grin:.

I think a link to the Github releases would be great, they are the main "truth" for release notes. Google Play release notes will always only be a subset of that.

**Comment by IzzySoft** [comment]
OK, added the link then. Might also serve as motivation :stuck_out_tongue:
