### ISSUE TITLE
Clean up Overview tab

### ISSUE THREAD

**Issue by vertigo220** [d4rken-org/permission-pilot#161]
Since the point of an overview is to be able to quickly get an overall picture of things, the content in this tab could be reduced to make it less cluttered and easier/quicker to digest. Instead of every line repeating the same thing ("No. of apps..." and "(### user apps, ### system apps), this repetitive text could be removed. There are different possible ways of doing this, e.g.:

- Table format, with 1A being "No./# of apps" (either No. or #, not both) and 1B being "User" and 1C being "System" then 2A being "In Active Profile" and 2B being "237" and 2C being "335" and so on
- With one line at top saying "No./# of total/user/system apps..." or "No./# of user system apps:" then each following line just having the remaining text (e.g. "in Active Profile" and "with 'Install from Unknown Sources' enabled") followed by just the app numbers in user/system format (e.g. 572/237/335). This could be separated by something other than a slash as well, e.g. 572=237+335 and/or they could be color-coded (user in green, system in red, total in yellow.
- At the very least, replaces "No. of apps" on each line with "Apps" so e.g. "No. of apps in Active Profile" would become simply "Apps in Active Profile" (I was going to say to just use "#" but there would be no reference as to number of what) and then remove the word apps on all the other lines, so "572 apps (237 user apps, 335 system apps)" would just become "572 (237 user, 335 system)"

**Comment by d4rken** [comment]
All good ideas, unfortunately I don't have the time for the bigger changes. I have removed the `No. of apps`. Not sure how familiar you are with Android, if you have time feel free to submit a pull request to further improve this. :pray:
