### ISSUE TITLE
Missing icons on "Calls" permissions

### ISSUE THREAD

**Issue by vertigo220** [d4rken-org/permission-pilot#166]
Aside from the "Other" category, where it can be tricky coming up with icons for some of the permissions, all other categories have an icon next to each permission when expanded, except the "Calls" category, which has a phone icon next to the first five then a blank space next to the last three (PROCESS_OUTGOING_CALLS, ADD_VOICEMAIL, and MANAGE_ONGOING_CALLS). This makes it look like either they didn't render or there's something special about these, but it seems to me it's just a case of them being missed when assigning icons.

**Comment by d4rken** [comment]
Good point, thank you!
