### ISSUE TITLE
Can't open the app

### ISSUE THREAD

**Issue by Super12138** [d4rken-org/permission-pilot#186]
When I open this app, the app will immediately exit.
You can watch this video to find out the problem better.
<video src="https://github.com/d4rken-org/permission-pilot/assets/70494801/dccc5476-5802-48b0-9e55-56e40e1e2070"></video>

**Comment by d4rken** [comment]
Please state your device type and Android version.
I'll also need the stacktrace of the crash, you can get it via logcat or from a system bug report.

**Comment by d4rken** [comment]
Looks like Permission Pilot is overloading your system and it's crashing. How many apps do you have installed?

**Comment by Super12138** [comment]
> Looks like Permission Pilot is overloading your system and it's crashing. How many apps do you have installed?

I installed 131 user apps.

**Comment by d4rken** [comment]
The only thing I see is to reduce the parallelism. For Android 10 it is currently at `2`, we could set it to `1` :thinking: 

https://github.com/d4rken-org/permission-pilot/blob/24add8c9a76d051c425d4c84be1b67fe1ebe5597/app/src/main/java/eu/darken/myperm/common/IPCFunnel.kt#L28-L34
