### ISSUE TITLE
App icon wanted :rocket: 

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/permission-pilot#2]
:slightly_smiling_face: 

* https://developer.android.com/distribute/google-play/resources/icon-design-specifications
* https://material.io/design/platform-guidance/android-icons.html#usage
* https://material.io/design/iconography/product-icons.html#design-principles

**Comment by TheMysticS** [comment]
Suggestions: Replace the human icon with Android icon.

Suggestion #1

![Permissions](https://user-images.githubusercontent.com/54448474/179392865-ce550d10-7e1a-4fa3-a559-6f9ed6cf7ca2.png)


Suggestion #2

![permission-icon-1](https://user-images.githubusercontent.com/54448474/179392871-0e2d329e-89c6-4abd-ae25-c5cec984b03e.jpg)

**Comment by d4rken** [comment]
[Max](https://twitter.com/maxpatchs) has provided us with an awesome icon, so this is done :rocket:.

<img src="https://github.com/d4rken-org/permission-pilot/raw/main/.github/assets/app_banner.png" width="400">

**Comment by TheMysticS** [comment]
Awesome indeed. 😍😍
