### ISSUE TITLE
Filters app from Main Profile when listing apps in Work Profile 

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#55]
I haven't found another instance yet, but you'll see that EZ Gallery installed in Main Profile is having Work in its name:

![Screenshot_2022-07-20-17-34-10-93_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/179977991-dcd5b183-807c-46c9-8b8e-463ed52c53a9.jpg)

**Comment by d4rken** [comment]
Can't reproduce

**Comment by TheMysticS** [comment]
But this is app in the main profile.

So far, this is the only app that is showing up in my device with the wrong name.

**Comment by TheMysticS** [comment]
This problem appears to have been sorted out. I think you can close this.
