### ISSUE TITLE
Permission details for apps installed in other profiles 

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#60]
![Screenshot_2022-07-20-19-47-06-33_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/180005221-84088ec8-8675-43e5-a41b-8c06e474ab0b.jpg)

Can you replace the "0 of 24 permissions granted" with:

**24 permissions requested. 
Due to Android restrictions, it is not possible to show which permissions have been granted to apps installed in other profiles.**

Also, where permission status is not available, the icon indicator should be different.

**Comment by TheMysticS** [comment]
Can you make this be displayed in two lines, just as shown in OP?

**Comment by TheMysticS** [comment]
I have re-worded this as follows:

24 permissions requested.
Due to Android restrictions, it is not possible to determine which permissions have been granted to apps installed in Managed User Profiles, i.e. Work Profile and Multi-Users. Permission status can only be shown for apps in the Active Profile, i.e. profile where this app is installed.

**Comment by TheMysticS** [comment]
Alternate Wording:

**This app is installed in another user profile.
Permissions granted can be determined only for apps installed in the currently Active Profile, due to Android restriction.**

**Comment by d4rken** [comment]
New ticket or just send a PR 😉

**Comment by TheMysticS** [comment]
> New ticket or just send a PR 😉

Will do a PR. Just wanted your view before doing it.
