### ISSUE TITLE
Action for permission that are granted by default

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/permission-pilot#66]
See #22 and #65

Permissions that are granted by default when requested, e.g. internet permission

- [x] `android.permission.INTERNET`
- [x] TODO

While there is no action here, we can show the user an explanation.

**Comment by TheMysticS** [comment]
I hope this includes permissions like 'Change System Settings' and 'WiFi Control', both of which show under Special Access.

**Comment by d4rken** [comment]
All permissions that are neither `appop` nor `dangerous`:
https://developer.android.com/reference/android/Manifest.permission
