### ISSUE TITLE
App Crashes when clicking on Amazon Shopping app

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#69]
Amazon Shopping app is not installed in any of the profiles.

However, Amazon Music and Amazon Prime Video apps are installed.

Clicking on the Shopping app (probably some dependency) causes the app to crash.

![iMarkup_20220720_224645](https://user-images.githubusercontent.com/54448474/180043421-22e5ca43-000a-4075-8562-b3359ecb8144.jpg)

**Comment by d4rken** [comment]
Hm that looks like a preinstalled amazon shopping version for india. Does it show in SD Maid or system settings with more details?

**Comment by TheMysticS** [comment]
![Screenshot_2022-07-20-22-58-43-87_62f0e9ef2a35bdc7c62d39832d484c48](https://user-images.githubusercontent.com/54448474/180045318-5a40d771-4d57-45ab-9f0e-b444e3996656.jpg)

**Comment by TheMysticS** [comment]
Doesn't show up in System Settings.

**Comment by d4rken** [comment]
Can you check if this is fixed by #68?
If not please get me a stacktrace :+1:

**Comment by TheMysticS** [comment]
Amazon Music is now fine:

![Screenshot_2022-07-21-02-18-13-66_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/180079455-568b11d6-85ff-4805-a503-ce8ada695554.jpg)

But app still crashes when clicking on Shopping app.

**Comment by TheMysticS** [comment]
It is not just with Amazon Shopping, app crashes when clicking on any of the following:

![Screenshot_2022-07-21-02-26-29-34_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/180080804-a80a2530-4a6c-4081-ab70-11251410eb6a.jpg)

**Comment by TheMysticS** [comment]
Is it because none of these apps are actually installed?

**Comment by TheMysticS** [comment]
Here is a logcat:

[MPlogcat20220721.txt](https://github.com/d4rken-org/mystic-permissions/files/9157633/MPlogcat20220721.txt)

**Comment by d4rken** [comment]
> java.lang.NullPointerException: packageInfo.versionName must not be null

Ah okay, that's easy to fix, forgot it could be null.
