### ISSUE TITLE
Permission "how interesting is this" sort order

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/permission-pilot#70]
Permissions in app details are not well sorted, we should sort them.

Suggestion:
* Primary sort order: GRANTED/DENIED/UNKNOWN
* Secondary sort order: Interest level

The second sort will be based on a number that we manually give each of the known permissions. We create a sort order similar to how the system shows the permissions to create a familiar experience for the user.

**Comment by d4rken** [comment]
Hm, though the system sorts them by name, maybe we just need categories with a sort order and give permissions that the system also lists in the "permission manager" a common category.

**Comment by d4rken** [comment]
```kotlin
enum class VisibilityCategory {
MAIN,
SECONDARY,
UNKNOWN
}
```

Give category `MAIN` to all of these:
![Uploading Screenshot from 2022-07-20 21-43-45.png…]()

**Comment by TheMysticS** [comment]
Or should it be:

1. Managed by User
2. Managed by System

**Comment by TheMysticS** [comment]
On my phone, I already see 690 entries in the Permissions Tab.

Out of these, only those 30 or so are controlled by the user. Rest everything is managed by the System itself.

**Comment by TheMysticS** [comment]
Here are the permissions controllable by the user on a Samsung phone:

[Special Access](https://user-images.githubusercontent.com/54448474/180178893-236a1a66-2059-4bcf-a606-7c26d05eb40e.jpg)

[Permissions Manager](https://user-images.githubusercontent.com/54448474/180178987-e0666b24-2e69-4df6-b08b-7a09577fcf4c.jpg)

[Additional Permissions](https://user-images.githubusercontent.com/54448474/180179122-07813192-6864-4733-9427-25604ed2464c.png)

**Comment by d4rken** [comment]
> Here are the permissions controllable by the user on a Samsung phone:
> 
> [Special Access](https://user-images.githubusercontent.com/54448474/180178893-236a1a66-2059-4bcf-a606-7c26d05eb40e.jpg)
> 
> [Permissions Manager](https://user-images.githubusercontent.com/54448474/180178987-e0666b24-2e69-4df6-b08b-7a09577fcf4c.jpg)
> 
> [Additional Permissions](https://user-images.githubusercontent.com/54448474/180179122-07813192-6864-4733-9427-25604ed2464c.png)

Good, we need to map the "human readable name" to their ID now.
https://developer.android.com/reference/android/Manifest.permission

**Comment by dragonGod97677** [comment]
How about these for permission tab

Common: permissions in here are that can be seen on every app info settings, and the user can choose whether to allow the permission for an app or deny it

Uncommon: permissions in here are that scattered on the android settings, like accessibility, notification access, modify system settings, wifi control, and more. The user can choose whether to allow the permission for an app or deny it

User App/System defaults: These permissions are used by them to function properly, allowed by default and cannot be modified unless device is rooted or modifying the said app(s).

**Comment by TheMysticS** [comment]
@dragonGod97677 

Common here is what @d4rken referred to as Primary.

Uncommon is what he referred to as Secondary.

Both of these categories are what I clubbed together as Managed by User, and pretty much the only permissions that are important.

The rest of the permissions are not within user control (not without root) and probably shouldn't be tampered with either. As far as I understood, these are also necessary for the app to function properly without errors. Only users who fully understand these should touch them, and such users are a very small minority.

I have made my suggestions in #86 and #89. Do check them out and provide feedback.

**Comment by dragonGod97677** [comment]
> @dragonGod97677
> 
> Common here is what @d4rken referred to as Primary.
> 
> Uncommon is what he referred to as Secondary.
> 
> Both of these categories are what I clubbed together as Managed by User, and pretty much the only permissions that are important (from a user perspective).
> 
> The rest of the permissions are not within user control (not without root) and probably shouldn't be tampered with either. As far as I understood, these are also necessary for the app to function properly without errors. Only users who fully understand these should touch them, and such users are a very small minority.
> 
> I have made my suggestions in #86 and #89. Do check them out and provide feedback.

I didn't know there's names already to be used for sorting permissions 😅. 

Oh well, all is good now

**Comment by d4rken** [comment]
Adjusted for next release.

First sort order: Granted/Denied/Unknown
Second sort order: Known/Unknown permissions
Third sort order: Runtime permission, then special access, then everything else.
