### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#71]
Can we have the permissions icons start from the right of the red line:

![iMarkup_20220721_014155](https://user-images.githubusercontent.com/54448474/180073030-34701c14-2c8b-4d2e-94dd-1e0e34aa728b.jpg)

**Comment by d4rken** [comment]
And waste space on the left? :grin: 

![Screenshot from 2022-07-20 22-22-30](https://user-images.githubusercontent.com/1439229/180074623-9a915866-b053-4d46-9f10-477706e24c44.png)

**Comment by TheMysticS** [comment]
What is 'id' that is showing under some of the apps?

**Comment by d4rken** [comment]
The `id` already represents apps with a shared user id
