### ISSUE TITLE
Android 5 to 9 Links to system settings 

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken-org/permission-pilot#73]
> I've introduced the abstraction `PermissionAction` which we can now use to give each permission a custom action, e.g. open their respective system screen if that is possible:
> 
> https://github.com/d4rken-org/mystic-permissions/blob/ff577d72e866004f1db57175a70ddcf1e76a6a81/app/src/main/java/eu/darken/myperm/permissions/core/PermissionAction.kt
> 
> So we have to add each permission and it's action here: https://github.com/d4rken-org/mystic-permissions/blob/ff577d72e866004f1db57175a70ddcf1e76a6a81/app/src/main/java/eu/darken/myperm/permissions/core/known/AKnownPermissions.kt
> 
> Currently it all defaults to `None`

hey @d4rken can you use this activity `com.android.packageinstaller.permission.ui.ManagePermissionsActivity` to open this [Window](https://user-images.githubusercontent.com/38875906/180119777-bee69ce9-ef8e-4fd4-91fe-7bd0c9daf194.png) when tapping on a app's permission.
You can found that activity on `com.android.packageinstaller` and `com.google.android.packageinstaller`

**Comment by dragonGod97677** [comment]
Don't close this once you are done adding it, there's more, be right back

**Comment by dragonGod97677** [comment]
There's more activity but it goes to `com.android.settings.SubSettings`

I'll look more ways

**Comment by d4rken** [comment]
Would this be runtime permissions? (#65?)

> hey @d4rken can you use this activity com.android.packageinstaller.permission.ui.ManagePermissionsActivity to open this [Window](https://user-images.githubusercontent.com/38875906/180119777-bee69ce9-ef8e-4fd4-91fe-7bd0c9daf194.png) when tapping on a app's permission.

According this you need a system permission to open it:
https://stackoverflow.com/questions/31955872/how-to-jump-to-the-manage-permission-page-in-settings-app-with-code

**Comment by dragonGod97677** [comment]
> Would this be runtime permissions? (#65?)
> 
> > hey @d4rken can you use this activity com.android.packageinstaller.permission.ui.ManagePermissionsActivity to open this [Window](https://user-images.githubusercontent.com/38875906/180119777-bee69ce9-ef8e-4fd4-91fe-7bd0c9daf194.png) when tapping on a app's permission.
> 
> According this you need a system permission to open it: https://stackoverflow.com/questions/31955872/how-to-jump-to-the-manage-permission-page-in-settings-app-with-code

Both yes

We can just ask user once if they want it directly opening a app's permission settings but it requires a system permission that can be granted using ADB

**Comment by dragonGod97677** [comment]
> There's more Settings like access usage statistics but it goes to `com.android.settings.SubSettings`
> 
> I'll look more ways.

As for this one, `com.android.settings.Settings$UsageAccessSettingsActivity`

**Comment by dragonGod97677** [comment]
Apps Device Administration settings: `com.android.settings.DeviceAdminSettings`

**Comment by dragonGod97677** [comment]
Do not disturb access (maybe android 7 and above only?): `com.android.settings.Settings$ZenAccessSettingsActivity`

**Comment by dragonGod97677** [comment]
App's that uses Accessability service: `com.android.settings.Settings$AccessibilitySettingsActivity`

For apps request notification access: `com.android.settings.Settings$NotificationAccessSettingsActivity`

**Comment by dragonGod97677** [comment]
Apps uses Picture-in-Picture (maybe android 8 and above only?): `com.android.settings.Settings$PictureInPictureSettingsActivity`

Tbh, i don't know if the average user will have care for this permission...

**Comment by d4rken** [comment]
Thanks for the research @dragonGod97677 , good activites!
