### ISSUE TITLE
Re-ordering the Permissions Bar

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#77]
Can you rearrange the permission icons, putting the most important ones first, in this order:

1. Camera
2. Microphone
3. Precise/ Fine Location
4. Phone
5. Contacts
6. Call Logs
7. SMS
8. Storage
9. Install Unknown Apps
10. Accessibility Permissions
11. Device Admin
12. Appear on Top

The first 8 items are **Privacy** related, the next 4 are **Security** related.

I have left out Bluetooth, Control Vibration and Prevent phone from Sleeping, as the ones above are more important.

This is under the assumption that you'll show internet access and battery optimization status separately, as suggested in #72 .

**Comment by d4rken** [comment]
> Accessibility Permissions
> Device Admin
> Appear on Top

These are new, we don't show them at all currently?

> Accessibility Permissions
> Device Admin

There are special permissions that require extra checks too, need to add support for that first.

**Comment by TheMysticS** [comment]
I didn't see these permissions showing for any app, yet.
