### ISSUE TITLE
Crashes on older android versions (Android 7)

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken-org/permission-pilot#78]
[app_crash@oppo neo 5 android 7.1.1 custom rom.txt](https://github.com/d4rken-org/mystic-permissions/files/9160309/app_crash%40oppo.neo.5.android.7.1.1.custom.rom.txt)

[app_crash@oppo neo 5 android 5.1.1.txt](https://github.com/d4rken-org/mystic-permissions/files/9160313/app_crash%40oppo.neo.5.android.5.1.1.txt)

Edit: it was android 7.1.2 not 7.1.1

**Comment by d4rken** [comment]
https://github.com/d4rken-org/mystic-permissions/blob/790d6b2e7f2bb3c69c7656ad4516ccc370bc7e48/app/src/main/java/eu/darken/myperm/apps/core/container/SecondaryProfilePkg.kt#L72

`LauncherApps.getProfiles` is API 26 (Android 8).
https://developer.android.com/reference/android/content/pm/LauncherApps#getProfiles()
The method for the activity list is API21, but we need a `UserHandle` if we can't get it from `getProfiles()` maybe from somewhere else... 🤔
