### ISSUE TITLE
Check status of accessibility services 

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/permission-pilot#83]
Can we even determine this? If an app has such a service?

**Comment by TheMysticS** [comment]
SD Maid uses Accessibility Service to clear app cache on non-rooted phones. Apps that request access to Accessibility Service show up in a dedicated section within System Settings.

**Comment by x13a** [comment]
There are more to find..

* android.permission.BIND_NOTIFICATION_LISTENER_SERVICE
* android.permission.BIND_SCREENING_SERVICE
* android.permission.BIND_CALL_REDIRECTION_SERVICE
* android.permission.BIND_QUICK_SETTINGS_TILE
* android.permission.BIND_JOB_SERVICE

**Comment by x13a** [comment]
https://developer.android.com/reference/kotlin/android/view/accessibility/AccessibilityManager#getInstalledAccessibilityServiceList()

**Comment by d4rken** [comment]
> https://developer.android.com/reference/kotlin/android/view/accessibility/AccessibilityManager#getInstalledAccessibilityServiceList()

I'll try that. Permission wise the `BIND_ACCESSIBILITY_SERVICE` permission isn't directly declared, I think.. :thinking:

**Comment by d4rken** [comment]
afaik, this doesn't show up in `packageInfo.requestedPermissions` or `packageInfo.permissions`.

**Comment by d4rken** [comment]
Activity for it: https://github.com/d4rken-org/permission-pilot/issues/73#issuecomment-1193248012
