### ISSUE TITLE
Remove clones from SharedUserID

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#92]
![Screenshot_20220726-201901_Permission Pilot](https://user-images.githubusercontent.com/54448474/181038173-30bab6a3-65a5-429f-91e4-2265646432ae.png)

As you can see in the screenshot above, clone in the Work Profile shows up under SharedUserID. A clone being the same app, shouldn't show up under SharedUserID.

**Comment by TheMysticS** [comment]
What is strange here is that I also have Firefox Focus installed in both Main Profile and Work Profile, but this problem isn't there for Firefox Focus. Why?

**Comment by TheMysticS** [comment]
Although this ticket is now sorted, can you tell me which app is the Firefox app sharing it's ID with? Does it have to be one of the other apps from Mozilla on Google Play Store:

![Screenshot_20220727-163110_Google Play Store](https://user-images.githubusercontent.com/54448474/181231882-f368a2ed-813b-4fd4-8f80-e8a15ddf9526.png)

We know it is not Firefox Focus. So does it have to be one or more of the other 3 apps in the screenshot above?

**Comment by d4rken** [comment]
> Although this ticket is now sorted, can you tell me which app is the Firefox app sharing it's ID with? Does it have to be one of the other apps from Mozilla on Google Play Store:

None. It was sharing the ID with itself in another profile. as far as I know a sharedID with itself does not grant extra options as cross-profile communication between apps is restricted.

**Comment by TheMysticS** [comment]
> > Although this ticket is now sorted, can you tell me which app is the Firefox app sharing it's ID with? Does it have to be one of the other apps from Mozilla on Google Play Store:
> 
> None. It was sharing the ID with itself in another profile. as far as I know a sharedID with itself does not grant extra options as cross-profile communication between apps is restricted.

Quite strange. Then why isn't the same showing up for Firefox Focus or other apps cloned in the Work Profile?

**Comment by d4rken** [comment]
They probably don't have a sharedID set
