### ISSUE TITLE
Remove bug-tracking & internet permission from Permission Pilot?

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/permission-pilot#94]
Putting this up for discussion again.

Pro:

* Smaller app due to less dependencies
* Best possible privacy (due to no internet permission for this app to function, or is there a feature idea that will require internet?)
* Less hassle with Google Play data safety forms

Con:

* Bugs may only be fixed if user actively contacts me and can provide a stacktrace
* Bugs are more difficult to fix as Bugsnag error reporting is better than Google Play's

**Comment by TheMysticS** [comment]
How about a helper app (or a plugin) that users can download when required to provide you with the required stacktrace or logs?

**Comment by d4rken** [comment]
> How about a helper app (or a plugin) that users can download when required to provide you with the required stacktrace or logs?

More work than it's worth.

**Comment by d4rken** [comment]
Google rejected the initial APK over Bugsnag due to either my privacy policy not being correct, or me not having a prominent enough disclosure in the app, or how I filled out the data usage form.

I have no stomach to play cat and mouse with Google's AI around this, so I'm removing it until we have a million users :shrug:.

**Comment by TheMysticS** [comment]
> Google rejected the initial APK over Bugsnag due to either my privacy policy not being correct, or me not having a prominent enough disclosure in the app, or how I filled out the data usage form.
> 
> I have no stomach to play cat and mouse with Google's AI around this, so I'm removing it until we have a million users 🤷.
>
That doesn't sound good. Aren't these compliance requirements largely a copy-paste thing? I mean could you not copy the stuff for SD Maid into this app's application?

For now, while the Cons you mentioned in OP are genuine considerations, why don't you postpone this decision for the future? Let the app not have any sort of tracking or internet permissions. You can have a one-line privacy policy: 

**The app neither collects nor allows 3rd party services to collect any user data. Not even anonymously.**

Remember to lock all features and settings before submitting the APK again. Apparently, once you provide a feature for free, you cannot lock it behind a paywall in future.

**Comment by d4rken** [comment]
> Aren't these compliance requirements largely a copy-paste thing? 

Theoretically yes, practically no. It really depends on who/what reviews the app.
I removed it for now. Not up for guessing game what exactly Google wants to comply with that rule.

> The app neither collects nor allows 3rd party services to collect any user data. Not even anonymously.

That's good, added it to the policy.

**Comment by TheMysticS** [comment]
> Theoretically yes, practically no. It really depends on who/what reviews the app. I removed it for now. Not up for guessing game what exactly Google wants to comply with that rule.
> 
From the little that I know on this subject, a lot of reviews are done by bots or bot-equivalent humans. 😂🤣
