### ISSUE TITLE
Apps that use Chrome

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#99]
This is a strange app: [Beebom](https://play.google.com/store/apps/details?id=com.beebom.app.beebom) 

It doesn't require any permission at all, but still connects to internet using Chrome or other web browsers (usually Chromium based browsers).

Do we need a special classification for such apps?

**Comment by d4rken** [comment]
afaik, the app can't do internet things in the background, only when the user interacts with the built-in webbrowser.

I don't think this can be detected.

**Comment by TheMysticS** [comment]
> afaik, the app can't do internet things in the background, only when the user interacts with the built-in webbrowser.
> 
> I don't think this can be detected.

This app doesn't even have a built-in browser. It uses Chrome. If you disable Chrome, it uses Edge. Disable Edge, it uses Brave. And so on.

And once it uses a browser, it will make it impossible to remove its cookies from the browser:

![Screenshot_20220727-025923_Chrome](https://user-images.githubusercontent.com/54448474/181115743-4ac47d96-26e9-4866-8c45-aef86812fdfe.png)

The only way to remove those cookies is by resetting the browser (deleting browser app data).

Pretty annoying app.

**Comment by d4rken** [comment]
I don't think there is something that can be done about this within the scope of this app.
